version: 0.0
Resources:
  - TargetService:
    Type: AWS:ECS::Service
    Properties:
      TaskDefinition: "arn:aws:ecs:us-east-2:976104566718:task-definition/capstone:1"
      LoadBalancerInfo:
        ContainerName: "capstone-website"
        ContainerPort: 80
    PlatformVersion: "LATEST"
